insert into item ("imgUrl", price, title) values ('mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla', 2156, 'pellentesque volutpat');
insert into item ("imgUrl", price, title) values ('posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 4296, 'tortor');
insert into item ("imgUrl", price, title) values ('sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 5706, 'donec posuere metus vitae');
insert into item ("imgUrl", price, title) values ('lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', 1928, 'augue a suscipit');
insert into item ("imgUrl", price, title) values ('tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 5099, 'enim sit amet');
insert into item ("imgUrl", price, title) values ('phasellus sit amet erat nulla tempus vivamus in felis eu', 3026, 'integer a nibh in quis justo');
insert into item ("imgUrl", price, title) values ('venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', 3842, 'eget orci vehicula condimentum curabitur');
insert into item ("imgUrl", price, title) values ('nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 2631, 'sed sagittis');
insert into item ("imgUrl", price, title) values ('nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', 5707, 'ornare consequat lectus in est');
insert into item ("imgUrl", price, title) values ('in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices', 3937, 'ante vestibulum ante');
insert into item ("imgUrl", price, title) values ('leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', 5327, 'elit proin interdum mauris');
insert into item ("imgUrl", price, title) values ('integer pede justo lacinia eget tincidunt eget tempus vel pede', 1508, 'turpis sed');
insert into item ("imgUrl", price, title) values ('elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis', 2045, 'pede posuere nonummy integer');
insert into item ("imgUrl", price, title) values ('ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', 1325, 'blandit mi in');
insert into item ("imgUrl", price, title) values ('vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 4467, 'fermentum donec ut mauris eget massa');
insert into item ("imgUrl", price, title) values ('ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 5616, 'erat tortor sollicitudin mi');
insert into item ("imgUrl", price, title) values ('bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', 3383, 'eu massa donec dapibus');
insert into item ("imgUrl", price, title) values ('a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis', 1166, 'sed tristique in tempus sit amet');
insert into item ("imgUrl", price, title) values ('tempus semper est quam pharetra magna ac consequat metus sapien ut', 2517, 'congue vivamus metus arcu adipiscing molestie');
insert into item ("imgUrl", price, title) values ('duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque', 2291, 'gravida sem praesent');
insert into item ("imgUrl", price, title) values ('justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et', 4749, 'cras pellentesque volutpat dui');
insert into item ("imgUrl", price, title) values ('integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum', 3479, 'quam pede');
insert into item ("imgUrl", price, title) values ('sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 1222, 'massa');
insert into item ("imgUrl", price, title) values ('odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', 2928, 'tellus nulla ut erat');
insert into item ("imgUrl", price, title) values ('vivamus tortor duis mattis egestas metus aenean fermentum donec ut', 5046, 'lacus morbi sem mauris laoreet');
insert into item ("imgUrl", price, title) values ('at turpis a pede posuere nonummy integer non velit donec diam neque', 2025, 'lectus vestibulum quam sapien varius');
insert into item ("imgUrl", price, title) values ('ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris', 3536, 'nonummy integer non velit donec diam');
insert into item ("imgUrl", price, title) values ('donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 2960, 'elit proin');
insert into item ("imgUrl", price, title) values ('ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', 3762, 'massa tempor convallis nulla neque');
insert into item ("imgUrl", price, title) values ('congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', 5230, 'sollicitudin vitae consectetuer');
insert into item ("imgUrl", price, title) values ('neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus', 5030, 'tristique in');
insert into item ("imgUrl", price, title) values ('nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', 1732, 'nullam varius nulla facilisi');
insert into item ("imgUrl", price, title) values ('nulla tellus in sagittis dui vel nisl duis ac nibh', 1793, 'orci luctus et');
insert into item ("imgUrl", price, title) values ('pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 5988, 'sed vestibulum');
insert into item ("imgUrl", price, title) values ('morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 4443, 'non mauris morbi non lectus aliquam');
insert into item ("imgUrl", price, title) values ('fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 3291, 'dolor');
insert into item ("imgUrl", price, title) values ('egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque', 3581, 'leo odio porttitor id');
insert into item ("imgUrl", price, title) values ('pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', 5627, 'quis');
insert into item ("imgUrl", price, title) values ('lectus in est risus auctor sed tristique in tempus sit amet sem fusce', 4074, 'felis');
insert into item ("imgUrl", price, title) values ('vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate', 2370, 'id consequat in consequat ut nulla');
insert into item ("imgUrl", price, title) values ('at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 3120, 'mi pede malesuada in');
insert into item ("imgUrl", price, title) values ('dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 5360, 'nulla sed vel enim sit');
insert into item ("imgUrl", price, title) values ('ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', 2066, 'sagittis nam congue');
insert into item ("imgUrl", price, title) values ('semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac', 4772, 'aliquam non mauris morbi non lectus');
insert into item ("imgUrl", price, title) values ('montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', 1776, 'id nisl venenatis lacinia');
insert into item ("imgUrl", price, title) values ('quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 4800, 'semper rutrum nulla nunc purus phasellus');
insert into item ("imgUrl", price, title) values ('odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', 5978, 'diam cras');
insert into item ("imgUrl", price, title) values ('ac neque duis bibendum morbi non quam nec dui luctus rutrum', 1778, 'vestibulum ante ipsum primis in');
insert into item ("imgUrl", price, title) values ('gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 4974, 'sem fusce');
insert into item ("imgUrl", price, title) values ('pellentesque quisque porta volutpat erat quisque erat eros viverra eget', 3419, 'integer non');
insert into item ("imgUrl", price, title) values ('eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa', 4574, 'varius integer ac leo pellentesque');
insert into item ("imgUrl", price, title) values ('odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', 5945, 'at diam nam tristique tortor');
insert into item ("imgUrl", price, title) values ('non lectus aliquam sit amet diam in magna bibendum imperdiet', 3958, 'luctus rutrum');
insert into item ("imgUrl", price, title) values ('odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est', 4614, 'mus');
insert into item ("imgUrl", price, title) values ('nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis', 1398, 'erat eros');
insert into item ("imgUrl", price, title) values ('lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet', 1412, 'ipsum aliquam non mauris morbi non');
insert into item ("imgUrl", price, title) values ('dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris', 1598, 'vitae ipsum aliquam non mauris morbi');
insert into item ("imgUrl", price, title) values ('porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', 3951, 'fusce congue diam id');
insert into item ("imgUrl", price, title) values ('ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna', 4665, 'volutpat convallis morbi odio odio elementum');
insert into item ("imgUrl", price, title) values ('dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', 2106, 'congue diam id');
insert into item ("imgUrl", price, title) values ('id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 3453, 'nunc vestibulum ante');
insert into item ("imgUrl", price, title) values ('potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 4276, 'sapien in sapien iaculis congue');
insert into item ("imgUrl", price, title) values ('tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', 4063, 'leo rhoncus sed vestibulum');
insert into item ("imgUrl", price, title) values ('nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', 4609, 'purus aliquet');
insert into item ("imgUrl", price, title) values ('amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 4846, 'felis sed');
insert into item ("imgUrl", price, title) values ('ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', 4464, 'fusce congue diam id ornare');
insert into item ("imgUrl", price, title) values ('donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 2061, 'vivamus vel nulla eget eros elementum');
insert into item ("imgUrl", price, title) values ('consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 1168, 'condimentum neque sapien placerat ante nulla');
insert into item ("imgUrl", price, title) values ('tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum', 3133, 'eget massa');
insert into item ("imgUrl", price, title) values ('vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci', 2839, 'odio porttitor');
insert into item ("imgUrl", price, title) values ('a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', 5862, 'vivamus tortor duis mattis egestas');
insert into item ("imgUrl", price, title) values ('tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 3469, 'congue etiam justo etiam pretium');
insert into item ("imgUrl", price, title) values ('rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem', 1119, 'ante ipsum primis');
insert into item ("imgUrl", price, title) values ('nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus', 2490, 'etiam justo etiam pretium iaculis justo');
insert into item ("imgUrl", price, title) values ('posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', 3376, 'sit amet eros suspendisse accumsan tortor');
insert into item ("imgUrl", price, title) values ('consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 5933, 'sit amet nulla quisque');
insert into item ("imgUrl", price, title) values ('vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 4776, 'bibendum imperdiet nullam');
insert into item ("imgUrl", price, title) values ('id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 5108, 'vestibulum ante ipsum');
insert into item ("imgUrl", price, title) values ('platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat', 2679, 'mi in porttitor');
insert into item ("imgUrl", price, title) values ('ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede', 5723, 'amet cursus id turpis integer aliquet');
insert into item ("imgUrl", price, title) values ('vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros', 1796, 'nullam orci pede venenatis');
insert into item ("imgUrl", price, title) values ('semper sapien a libero nam dui proin leo odio porttitor id', 5456, 'ac');
insert into item ("imgUrl", price, title) values ('pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit', 4764, 'lacinia eget');
insert into item ("imgUrl", price, title) values ('morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', 3074, 'sollicitudin ut');
insert into item ("imgUrl", price, title) values ('montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum', 5102, 'nunc commodo placerat');
insert into item ("imgUrl", price, title) values ('nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', 4369, 'dapibus nulla suscipit ligula in');
insert into item ("imgUrl", price, title) values ('donec ut mauris eget massa tempor convallis nulla neque libero convallis', 2668, 'justo');
insert into item ("imgUrl", price, title) values ('eget nunc donec quis orci eget orci vehicula condimentum curabitur', 4071, 'mauris lacinia sapien quis libero nullam');
insert into item ("imgUrl", price, title) values ('dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', 2271, 'lectus in est risus auctor sed');
insert into item ("imgUrl", price, title) values ('sapien urna pretium nisl ut volutpat sapien arcu sed augue', 2327, 'leo rhoncus');
insert into item ("imgUrl", price, title) values ('molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 5286, 'vulputate');
insert into item ("imgUrl", price, title) values ('luctus cum sociis natoque penatibus et magnis dis parturient montes', 2409, 'rhoncus');
insert into item ("imgUrl", price, title) values ('habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id', 3890, 'venenatis tristique fusce congue diam id');
insert into item ("imgUrl", price, title) values ('iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 1229, 'dolor');
insert into item ("imgUrl", price, title) values ('ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', 3489, 'ut at dolor quis odio');
insert into item ("imgUrl", price, title) values ('et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices', 4909, 'sed');
insert into item ("imgUrl", price, title) values ('nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus', 5931, 'semper est quam pharetra magna');
insert into item ("imgUrl", price, title) values ('magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis', 3636, 'et ultrices posuere');
insert into item ("imgUrl", price, title) values ('cum sociis natoque penatibus et magnis dis parturient montes nascetur', 3000, 'ante vestibulum ante ipsum');
insert into item ("imgUrl", price, title) values ('justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 1327, 'sapien urna pretium nisl');
